version: '3.8'

services:
  nest-app:
    container_name: nest-app
    build:
      context: ./app
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka  # opcional, se estiver no mesmo compose
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
